### ISSUE TITLE
MultipartEncoder fields will not take file-like objects(Urllib2Response) but only file objects.

### ISSUE THREAD

**Issue by rockcollins** [requests/toolbelt#191]
`MultipartEncoder(fields={'fields': ('fields1', data, 'image/png')})`
While data is a object of Urllib2Response. This is for not loading 'data' to the memory.

```
Traceback (most recent call last):
  File "C:/Users/aaa/aaa.py", line 12, in <module>
    m = MultipartEncoder(fields={'content': ('dummy', data, data.headers.getheader('Content-Type'))})
  File "C:\Python27\lib\site-packages\requests_toolbelt\multipart\encoder.py", line 119, in __init__
    self._prepare_parts()
  File "C:\Python27\lib\site-packages\requests_toolbelt\multipart\encoder.py", line 240, in _prepare_parts
    self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
  File "C:\Python27\lib\site-packages\requests_toolbelt\multipart\encoder.py", line 490, in from_field
    return cls(headers, body)
  File "C:\Python27\lib\site-packages\requests_toolbelt\multipart\encoder.py", line 483, in __init__
    self.len = len(self.headers) + total_len(self.body)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by sigmavirus24** [comment]
Correct. We do not support this use case. You could definitely compose the `StreamingIterator` with tihs to do this. In other words, you could do something like:

```
from requests_toolbelt.streaming_iterator import StreamingIterator

def create_image_generator(data, chunk_size=(8192 * 10)):
    def generator():
        chunk = data.read(chunk_size)
        while chunk:
             yield chunk
             chunk = data.read(chunk_size)
        yield ''


image_size = get_image_size_from(data)
streaming_image = StreamingIterator(image_size, create_image_generator(data))
encoder = MultipartEncoder(fields={'fields': ('fields1', streaming_image, 'image/png')})
```

I think the reason you're seeing this error though is that `total_len` picks up an attribute that `urllib2` sets to `None` which means we cannot determine the size in advance of uploading it. An alternative would be to set the attribute causing it to return `None`.
